### ISSUE TITLE
script.js is not drawing correctly

### ISSUE THREAD

**Issue by derhuerst** [embrilliant/VideoPaint-Advanced#1]
(This is for the sake of documentation.)

`script.js` is not drawing correctly. The frames from the HTML5 videos are not drawn to the _output_ canvas.

**Comment by derhuerst** [comment]
@embrilliant 

This might help you: https://hacks.mozilla.org/2014/03/introducing-the-canvas-debugger-in-firefox-developer-tools/

**Comment by embrilliant** [comment]
@derhuerst 
I cleaned up script.js. With script.js it is working.

**Comment by embrilliant** [comment]
Thanks for the link.

**Comment by derhuerst** [comment]
Did you know that you can reference commits in issues? Just use the 7-character short commit id (for example `915bc62`). The result: 915bc62.

**Comment by derhuerst** [comment]
I saw that you applied the best practices (e.g. writing reusable functions), but you could do it even further by separating the drawing and the event logic, like we tried with `script2.js` (and didn't finish :laughing:).

**Comment by embrilliant** [comment]
915bc62 no I didn't know. Cool, thanks.

**Comment by derhuerst** [comment]
Github uses GitHub Flavored Markdown, an extended version of [Markdown](https://daringfireball.net/projects/markdown/). You can read about it here:
- [Markdown Basics](https://help.github.com/articles/markdown-basics/) from the Github help pages
- [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/#differences-from-traditional-markdown) from the Github help pages
- [Writing on GitHub](https://help.github.com/articles/writing-on-github/#markup) from the Github help pages

**Comment by embrilliant** [comment]
@derhuerst Thank you.

**Comment by derhuerst** [comment]
And I have Emojis for you: http://www.emoji-cheat-sheet.com/

The best one: :shipit:

**Comment by embrilliant** [comment]
EMOJI on github? :octocat:
